function printNewLH(request, response) {
    var invID = request.getParameter("recid");
    var purchRec = nlapiLoadRecord('purchaseorder', 10792);
    var renderer = nlapiCreateTemplateRenderer();
    var template = '';
    template += '<?xml version="1.0"?><!DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd">';
    template += '<pdf>';
    template += '<head>';
    template += '	<link name="NotoSans" type="font" subtype="truetype" src="${nsfont.NotoSans_Regular}" src-bold="${nsfont.NotoSans_Bold}" src-italic="${nsfont.NotoSans_Italic}" src-bolditalic="${nsfont.NotoSans_BoldItalic}" bytes="2" />';
    template += '	<#if .locale == "zh_CN">';
    template += '		<link name="NotoSansCJKsc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKsc_Regular}" src-bold="${nsfont.NotoSansCJKsc_Bold}" bytes="2" />';
    template += '	<#elseif .locale == "zh_TW">';
    template += '		<link name="NotoSansCJKtc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKtc_Regular}" src-bold="${nsfont.NotoSansCJKtc_Bold}" bytes="2" />';
    template += '	<#elseif .locale == "ja_JP">';
    template += '		<link name="NotoSansCJKjp" type="font" subtype="opentype" src="${nsfont.NotoSansCJKjp_Regular}" src-bold="${nsfont.NotoSansCJKjp_Bold}" bytes="2" />';
    template += '	<#elseif .locale == "ko_KR">';
    template += '		<link name="NotoSansCJKkr" type="font" subtype="opentype" src="${nsfont.NotoSansCJKkr_Regular}" src-bold="${nsfont.NotoSansCJKkr_Bold}" bytes="2" />';
    template += '	<#elseif .locale == "th_TH">';
    template += '		<link name="NotoSansThai" type="font" subtype="opentype" src="${nsfont.NotoSansThai_Regular}" src-bold="${nsfont.NotoSansThai_Bold}" bytes="2" />';
    template += '	</#if>';
    template += '    <macrolist>';
    template += '        <macro id="nlheader">';
    template += '            <table class="header" style="width: 100%;"><tr>';
    template += '	<td rowspan="3"><#if companyInformation.logoUrl?length != 0><img src="${companyInformation.logoUrl}" style="float: left; margin: 7px" /> </#if> <span class="nameandaddress">${companyInformation.companyName}</span><br /><span class="nameandaddress">${companyInformation.addressText}</span></td>';
    template += '	<td align="right"><span class="title">${record@title}</span></td>';
    template += '	</tr>';
    template += '	<tr>';
    template += '	<td align="right"><span class="number">#${record.tranid}</span></td>';
    template += '	</tr>';
    template += '	<tr>';
    template += '	<td align="right">${record.trandate}</td>';
    template += '	</tr></table>';
    template += '        </macro>';
    template += '        <macro id="nlfooter">';
    template += '            <table class="footer" style="width: 100%;"><tr>';
    template += '	<td><barcode codetype="code128" showtext="true" value="${record.tranid}"/></td>';
    template += '	<td align="right"><pagenumber/> of <totalpages/></td>';
    template += '	</tr></table>';
    template += '        </macro>';
    template += '    </macrolist>';
    template += '    <style type="text/css">* {';
    template += '		<#if .locale == "zh_CN">';
    template += '			font-family: NotoSans, NotoSansCJKsc, sans-serif;';
    template += '		<#elseif .locale == "zh_TW">';
    template += '			font-family: NotoSans, NotoSansCJKtc, sans-serif;';
    template += '		<#elseif .locale == "ja_JP">';
    template += '			font-family: NotoSans, NotoSansCJKjp, sans-serif;';
    template += '		<#elseif .locale == "ko_KR">';
    template += '			font-family: NotoSans, NotoSansCJKkr, sans-serif;';
    template += '		<#elseif .locale == "th_TH">';
    template += '			font-family: NotoSans, NotoSansThai, sans-serif;';
    template += '		<#else>';
    template += '			font-family: NotoSans, sans-serif;';
    template += '		</#if>';
    template += '		}';
    template += '		table {';
    template += '			font-size: 9pt;';
    template += '			table-layout: fixed;';
    template += '		}';
    template += '        th {';
    template += '            font-weight: bold;';
    template += '            font-size: 8pt;';
    template += '            vertical-align: middle;';
    template += '            padding: 5px 6px 3px;';
    template += '            background-color: #e3e3e3;';
    template += '            color: #333333;';
    template += '        }';
    template += '        td {';
    template += '            padding: 4px 6px;';
    template += '        }';
    template += '		td p { align:left }';
    template += '        b {';
    template += '            font-weight: bold;';
    template += '            color: #333333;';
    template += '        }';
    template += '        table.header td {';
    template += '            padding: 0;';
    template += '            font-size: 10pt;';
    template += '        }';
    template += '        table.footer td {';
    template += '            padding: 0;';
    template += '            font-size: 8pt;';
    template += '        }';
    template += '        table.itemtable th {';
    template += '            padding-bottom: 10px;';
    template += '            padding-top: 10px;';
    template += '        }';
    template += '        table.body td {';
    template += '            padding-top: 2px;';
    template += '        }';
    template += '        table.total {';
    template += '            page-break-inside: avoid;';
    template += '        }';
    template += '        tr.totalrow {';
    template += '            background-color: #e3e3e3;';
    template += '            line-height: 200%;';
    template += '        }';
    template += '        td.totalboxtop {';
    template += '            font-size: 12pt;';
    template += '            background-color: #e3e3e3;';
    template += '        }';
    template += '        td.addressheader {';
    template += '            font-size: 8pt;';
    template += '            padding-top: 6px;';
    template += '            padding-bottom: 2px;';
    template += '        }';
    template += '        td.address {';
    template += '            padding-top: 0;';
    template += '        }';
    template += '        td.totalboxmid {';
    template += '            font-size: 28pt;';
    template += '            padding-top: 20px;';
    template += '            background-color: #e3e3e3;';
    template += '        }';
    template += '        td.totalboxbot {';
    template += '            background-color: #e3e3e3;';
    template += '            font-weight: bold;';
    template += '        }';
    template += '        span.title {';
    template += '            font-size: 28pt;';
    template += '        }';
    template += '        span.number {';
    template += '            font-size: 16pt;';
    template += '        }';
    template += '        span.itemname {';
    template += '            font-weight: bold;';
    template += '            line-height: 150%;';
    template += '        }';
    template += '        hr {';
    template += '            width: 100%;';
    template += '            color: #d3d3d3;';
    template += '            background-color: #d3d3d3;';
    template += '            height: 1px;';
    template += '        }';
    template += '</style>';
    template += '</head>';
    template += '<body header="nlheader" header-height="10%" footer="nlfooter" footer-height="20pt" padding="0.5in 0.5in 0.5in 0.5in" size="Letter">';
    template += '<br></br>';
    template += '<h3></h3>';
    template += '<table style="border:1px solid black; width:100%">';
    template += '	<tr> ';
    template += '		<td align="center" colspan="2">';
    template += '			<h1>Purchase Order</h1>';
    template += '		</td>';
    template += '	</tr>';
    template += '	<tr style="border-top:1px solid black;">';
    template += '		<td style="border-right:1px solid black;">Purchase no. :280898</td>';
    template += '		<td>Purchase Date:10-feb-2021</td>';
    template += '	</tr>';
    template += '</table>';
    template += '	<br>';
    template += '	</br>';
    template += '<table style="border:1px solid black;width:100%">';
    template += '	<tr>';
    template += '	<td style="border-right:1px solid black;">';
    template += '			<p>otherrefnum</p>';
    template += '			<P>AL0408</P>';
    template += '			<P>P.O Box 18220</P>';
    template += '			<P>Dubai </P>';
    template += '			<P>United Arab Emirates</P>';
    template += '			<P>TRN : 100236819700003</P>';
    template += '			<P>Tel # +97148872211</P>';
    template += '			<P>Fax # +97148872212</P>';
    template += '			<P>Attn : Bakker / Pragu</P>';
    template += '		</td>';
    template += '		<td style="border-right:1px solid black;">';
    template += '			<P>Contract: QT-L60477-21</P>';
    template += '			<P>LPO No:</P>';
    template += '			<P>PayTerms: 90 Days from Date of </P>';
    template += '	';
    template += '			<P>Invoice</P>';
    template += '			<P>Pay Due: 15-Feb-2022</P>';
    template += '			<P>Sales Rep: MELWYN D COSTA</P>';
    template += '			<P>Site: JAFZA / TECHNOPARK.</P>';
    template += '';
    template += '		</td>';
    template += '		<td style="border-right:1px solid black;">';
    template += '			<P>A/C No : 01289015101</P>';
    template += '			<P>IBAN No : AE490440000001289015101</P>';
    template += '			<P>STANDARD CHARTERED BANK </P>';
    template += '			<P>SWIFT No : SCBLAEADXXX</P>';
    template += '			<P>A/C Name : Al Faris Equipment</P>';
    template += '			<P>Rentals(L.L.C)</P>';
    template += '			<P>All bank transfer charges to be borne by customer</P>';
    template += '		</td>';
    template += '	</tr>';
    template += '';
    template += '	<tr colspan="3"  style="border-top:1px solid black;">';
    template += '		<td>Scope of Work</td>';
    template += '	</tr>';
    template += '</table>';
    template += '<#if record.item?has_content>';
    template += '<table style="border:1px solid black; width:100%; margin:20px;">';
    template += '	<tr>';
    template += '		<th style="border-right:1px solid black; width:8%"><b>Sl No.</b></th>';
    template += '		<th style="border-right:1px solid black;"><b>Item No.</b></th>';
    template += '		<th style="border-right:1px solid black;" align="right"><b>Rate</b></th>';
    template += '		<th style="border-right:1px solid black;" align="right"><b>Amount</b></th>';
    template += '	</tr>';
    template += '	<#assign totalrate=0>';
    template += '	<#assign slno=1>';
    template += '';
    template += '	<#list record.item as item>';
    template += '	<tr style="border-top:1px solid black;">';
    template += '		<td style="border-right:1px solid black;">${slno}</td>';
    template += '		<td style="border-right:1px solid black;">${item.item}</td>';
    template += '		<td style="border-right:1px solid black;" align="right">${item.rate?string("##,#00.00")}</td>';
    template += '		<td style="border-right:1px solid black;" align="right">${item.amount}</td>';
    template += '	</tr>';
    template += '	<#assign slno=slno + 1>';
    template += '	<#assign totalrate=totalrate + item.rate>';
    template += '	</#list>';
    template += '	<tr style="border-top:1px solid black;">';
    template += '		<td colspan="2" style="border-right:1px solid black;">Total</td>';
    template += '		<td style="border-right:1px solid black;" align="right">${totalrate}</td>';
    template += '		<td style="border-right:1px solid black;" align="right">${totalrate}</td>';
    template += '	</tr>';
    template += '</table>';
    template += '</#if>';
    template += '<table style="border: 1px solid black;">';
    template += '	<tr>';
    template += '		<th style="border-right:1px solid black;">IS Date</th>';
    template += '		<th style="border-right:1px solid black;">TS No.</th>';
    template += '		<th style="border-right:1px solid black;">Equipment</th>';
    template += '		<th style="border-right:1px solid black;">Description</th>';
    template += '		<th style="border-right:1px solid black;">Rential unit</th>';
    template += '		<th style="border-right:1px solid black;">Unit Price</th>';
    template += '		<th style="border-right:1px solid black;">Total excl.of Tax(AED)</th>';
    template += '		<th style="border-right:1px solid black;">Tax%</th>';
    template += '		<th style="border-right:1px solid black;">Tax(AED)</th>';
    template += '		<th style="border-right:1px solid black;">Total with Tax(AED)</th>';
    template += '	</tr>';
    template += '	<tr>';
    template += '		<td style="border-right:1px solid black;">30/9/2021<br></br> to<br></br> 3/9/2021</td>';
    template += '		<td style="border-right:1px solid black;">l297217</td>';
    template += '		<td style="border-right:1px solid black;">25 TON TRUCK<br></br> MOUNTED CRANE <br></br> Start Date:30/9/2021</td>';
    template += '		<td style="border-right:1px solid black;"></td>';
    template += '		<td style="border-right:1px solid black;">4 00 Hrs</td>';
    template += '		<td style="border-right:1px solid black;"></td>';
    template += '		<td style="border-right:1px solid black;">400 00</td>';
    template += '		<td style="border-right:1px solid black;">0 0</td>';
    template += '		<td style="border-right:1px solid black;">0 00</td>';
    template += '		<td style="border-right:1px solid black;">400 00</td>';
    template += '	</tr>';
    template += '		<tr style="border-top:1px solid black;">';
    template += '		<td colspan="6" style="border-right:1px solid black;">Total Value in AED</td>';
    template += '		<td style="border-right:1px solid black;">400.00</td>';
    template += '		<td style="border-right:1px solid black;"></td>';
    template += '		<td style="border-right:1px solid black;">0.00</td>';
    template += '		<td style="border-right:1px solid black;">400.00</td>';
    template += '	</tr>';
    template += '	<tr style="border-top:1px solid black;">';
    template += '	<td colspan="9" style="border-right:1px solid black;">Amount in words:<i> AED Four Hundred Only</i></td>';
    template += '	<td style="border-right:1px solid black;">400.00</td>';
    template += '	</tr>';
    template += '</table>';
    template += '<br></br>';
    template += '<br></br>';
    template += '<table>';
    template += '<tr>';
    template += '	<td></td>';
    template += '	<td><b>E.O.E</b></td>';
    template += '</tr>';
    template += '<tr>';
    template += '	<td>Received by:______________________</td>';
    template += '	';
    template += '	<td><b>For AI Faris Equipment Rentals(L.L.C)</b></td>';
    template += '';
    template += '</tr>';
    template += '<tr>';
    template += '	<td>Received date:____________________</td>';
    template += '	<td></td>';
    template += '	</tr>';
    template += '	<tr>';
    template += '	<td> <p> <i> Note:#Please ensure full name of company is printed on payment cheque as per Invoice </i> </p> </td>';
    template += '	<td></td>';
    template += '</tr>';
    template += '<tr>';
    template += '<td> </td>';
    template += '<td>';
    template += '<table>';
    template += '<tr>';
    template += '	<td>___________<br></br>perpared by</td>';
    template += '	<td> _____________<br></br>checked by</td>';
    template += '	<td>_____________<br></br> Approved by</td>';
    template += '</tr>';
    template += '</table>';
    template += '</td>';
    template += '</tr>';
    template += '</table>';
    template += '';
    template += '';
    template += '    <table style="width: 100%;"><tr>';
    template += '	<td class="addressheader" colspan="6"><b>${record.billaddress@label}</b></td>';
    template += '	<td class="totalboxtop" colspan="5"><b>${record.total@label?upper_case}</b></td>';
    template += '	</tr>';
    template += '	<tr>';
    template += '	<td class="address" colspan="6" rowspan="2">${record.billaddress}</td>';
    template += '	<td align="right" class="totalboxmid" colspan="5">${record.total}</td>';
    template += '	</tr>';
    template += '	<tr>';
    template += '	<td align="right" class="totalboxbot" colspan="5"><b>${record.duedate@label}:</b> ${record.duedate}</td>';
    template += '	</tr></table>';
    template += '';
    template += '<table class="body" style="width: 100%;"><tr>';
    template += '	<th>${record.duedate@label}</th>';
    template += '	<th>${record.otherrefnum@label}</th>';
    template += '	<th>${record.billphone@label}</th>';
    template += '	</tr>';
    template += '	<tr>';
    template += '	<td>${record.duedate}</td>';
    template += '	<td>${record.otherrefnum}</td>';
    template += '	<td>${record.billphone}</td>';
    template += '	</tr></table>';
    template += '<#if record.item?has_content>';
    template += '';
    template += '<table class="itemtable" style="width: 100%;"><!-- start items --><#list record.item as item><#if item_index==0>';
    template += '<thead>';
    template += '	<tr>';
    template += '	<th align="center" colspan="3">${item.quantity@label}</th>';
    template += '	<th colspan="12">${item.item@label}</th>';
    template += '	<th colspan="3">${item.options@label}</th>';
    template += '	<th align="right" colspan="4">${item.rate@label}</th>';
    template += '	<th align="right" colspan="4">${item.amount@label}</th>';
    template += '	</tr>';
    template += '</thead>';
    template += '</#if><tr>';
    template += '	<td align="center" colspan="3" line-height="150%">${item.quantity}</td>';
    template += '	<td colspan="12"><span class="itemname">${item.item}</span><br />${item.description}</td>';
    template += '	<td colspan="3">${item.options}</td>';
    template += '	<td align="right" colspan="4">${item.rate}</td>';
    template += '	<td align="right" colspan="4">${item.amount}</td>';
    template += '	</tr>';
    template += '	</#list><!-- end items --></table>';
    template += '</#if><#if record.expense?has_content>';
    template += '';
    template += '<table class="itemtable" style="width: 100%;"><!-- start expenses --><#list record.expense as expense ><#if expense_index==0>';
    template += '<thead>';
    template += '	<tr>';
    template += '	<th colspan="12">${expense.category@label}</th>';
    template += '	<th colspan="10">${expense.account@label}</th>';
    template += '	<th align="right" colspan="4">${expense.amount@label}</th>';
    template += '	</tr>';
    template += '</thead>';
    template += '</#if><tr>';
    template += '	<td colspan="12">${expense.category}</td>';
    template += '	<td colspan="10"><span class="itemname">${expense.account}</span></td>';
    template += '	<td align="right" colspan="4">${expense.amount}</td>';
    template += '	</tr>';
    template += '	</#list><!-- end expenses --></table>';
    template += '</#if>';
    template += '';
    template += '<hr />';
    template += '<table class="total" style="width: 100%;"><tr class="totalrow">';
    template += '	<td background-color="#ffffff" colspan="4">&nbsp;</td>';
    template += '	<td align="right"><b>${record.total@label}</b></td>';
    template += '	<td align="right">${record.total}</td>';
    template += '	</tr></table>';
    template += '</body>';
    template += '</pdf>';
    renderer.setTemplate(template);
    renderer.addRecord('record', purchRec);
    var xml = renderer.renderToString();
    var file = nlapiXMLToPDF(xml);
    response.setContentType('PDF', 'purchaseorder' + purchRec.getFieldValue("id") + '.pdf', 'inline');
    response.write(file.getValue());
}