function printNewLH(request, response) {
    var invID = request.getParameter("recid");
    var bb=9;
    var purchRec = nlapiLoadRecord('invoice', 10805);
    var renderer = nlapiCreateTemplateRenderer();
    var template = '';
    template = +'<?xml version="1.0"?><!DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd">';
    template = +'<pdf>';
    template = +'<head>';
    template = +'	<link name="NotoSans" type="font" subtype="truetype" src="${nsfont.NotoSans_Regular}" src-bold="${nsfont.NotoSans_Bold}" src-italic="${nsfont.NotoSans_Italic}" src-bolditalic="${nsfont.NotoSans_BoldItalic}" bytes="2" />';
    template = +'	<#if .locale == "zh_CN">';
    template = +'		<link name="NotoSansCJKsc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKsc_Regular}" src-bold="${nsfont.NotoSansCJKsc_Bold}" bytes="2" />';
    template = +'	<#elseif .locale == "zh_TW">';
    template = +'		<link name="NotoSansCJKtc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKtc_Regular}" src-bold="${nsfont.NotoSansCJKtc_Bold}" bytes="2" />';
    template = +'	<#elseif .locale == "ja_JP">';
    template = +'		<link name="NotoSansCJKjp" type="font" subtype="opentype" src="${nsfont.NotoSansCJKjp_Regular}" src-bold="${nsfont.NotoSansCJKjp_Bold}" bytes="2" />';
    template = +'	<#elseif .locale == "ko_KR">';
    template = +'		<link name="NotoSansCJKkr" type="font" subtype="opentype" src="${nsfont.NotoSansCJKkr_Regular}" src-bold="${nsfont.NotoSansCJKkr_Bold}" bytes="2" />';
    template = +'	<#elseif .locale == "th_TH">';
    template = +'		<link name="NotoSansThai" type="font" subtype="opentype" src="${nsfont.NotoSansThai_Regular}" src-bold="${nsfont.NotoSansThai_Bold}" bytes="2" />';
    template = +'	</#if>';
    template = +'    <macrolist>';
    template = +'        <macro id="nlheader">';
    template = +'            <table class="header" style="width: 100%;"><tr>';
    template = +'	<td rowspan="3"><#if companyInformation.logoUrl?length != 0><img src="${companyInformation.logoUrl}" style="float: left; margin: 7px" /> </#if> <span class="nameandaddress">${companyInformation.companyName}</span><br /><span class="nameandaddress">${companyInformation.addressText}</span></td>';
    template = +'	<td align="right"><span class="title">${record@title}</span></td>';
    template = +'	</tr>';
    template = +'	<tr>';
    template = +'	<td align="right"><span class="number">#${record.tranid}</span></td>';
    template = +'	</tr>';
    template = +'	<tr>';
    template = +'	<td align="right">${record.trandate}</td>';
    template = +'	</tr></table>';
    template = +'        </macro>';
    template = +'        <macro id="nlfooter">';
    template = +'            <table class="footer" style="width: 100%;"><tr>';
    template = +'	<td><barcode codetype="code128" showtext="true" value="${record.tranid}"/></td>';
    template = +'	<td align="right"><pagenumber/> of <totalpages/></td>';
    template = +'	</tr></table>';
    template = +'        </macro>';
    template = +'    </macrolist>';
    template = +'    <style type="text/css">* {';
    template = +'		<#if .locale == "zh_CN">';
    template = +'			font-family: NotoSans, NotoSansCJKsc, sans-serif;';
    template = +'		<#elseif .locale == "zh_TW">';
    template = +'			font-family: NotoSans, NotoSansCJKtc, sans-serif;';
    template = +'		<#elseif .locale == "ja_JP">';
    template = +'			font-family: NotoSans, NotoSansCJKjp, sans-serif;';
    template = +'		<#elseif .locale == "ko_KR">';
    template = +'			font-family: NotoSans, NotoSansCJKkr, sans-serif;';
    template = +'		<#elseif .locale == "th_TH">';
    template = +'			font-family: NotoSans, NotoSansThai, sans-serif;';
    template = +'		<#else>';
    template = +'			font-family: NotoSans, sans-serif;';
    template = +'		</#if>';
    template = +'		}';
    template = +'		table {';
    template = +'			font-size: 9pt;';
    template = +'			table-layout: fixed;';
    template = +'		}';
    template = +'        th {';
    template = +'            font-weight: bold;';
    template = +'            font-size: 8pt;';
    template = +'            vertical-align: middle;';
    template = +'            padding: 5px 6px 3px;';
    template = +'            background-color: #e3e3e3;';
    template = +'            color: #333333;';
    template = +'        }';
    template = +'        td {';
    template = +'            padding: 4px 6px;';
    template = +'        }';
    template = +'		td p { align:left }';
    template = +'        b {';
    template = +'            font-weight: bold;';
    template = +'            color: #333333;';
    template = +'        }';
    template = +'        table.header td {';
    template = +'            padding: 0px;';
    template = +'            font-size: 10pt;';
    template = +'        }';
    template = +'        table.footer td {';
    template = +'            padding: 0px;';
    template = +'            font-size: 8pt;';
    template = +'        }';
    template = +'        table.itemtable th {';
    template = +'            padding-bottom: 10px;';
    template = +'            padding-top: 10px;';
    template = +'        }';
    template = +'        table.body td {';
    template = +'            padding-top: 2px;';
    template = +'        }';
    template = +'        table.total {';
    template = +'            page-break-inside: avoid;';
    template = +'        }';
    template = +'        tr.totalrow {';
    template = +'            background-color: #e3e3e3;';
    template = +'            line-height: 200%;';
    template = +'        }';
    template = +'        td.totalboxtop {';
    template = +'            font-size: 12pt;';
    template = +'            background-color: #e3e3e3;';
    template = +'        }';
    template = +'        td.addressheader {';
    template = +'            font-size: 8pt;';
    template = +'            padding-top: 6px;';
    template = +'            padding-bottom: 2px;';
    template = +'        }';
    template = +'        td.address {';
    template = +'            padding-top: 0px;';
    template = +'        }';
    template = +'        td.totalboxmid {';
    template = +'            font-size: 28pt;';
    template = +'            padding-top: 20px;';
    template = +'            background-color: #e3e3e3;';
    template = +'        }';
    template = +'        td.totalboxbot {';
    template = +'            background-color: #e3e3e3;';
    template = +'            font-weight: bold;';
    template = +'        }';
    template = +'        span.title {';
    template = +'            font-size: 28pt;';
    template = +'        }';
    template = +'        span.number {';
    template = +'            font-size: 16pt;';
    template = +'        }';
    template = +'        span.itemname {';
    template = +'            font-weight: bold;';
    template = +'            line-height: 150%;';
    template = +'        }';
    template = +'        hr {';
    template = +'            width: 100%;';
    template = +'            color: #d3d3d3;';
    template = +'            background-color: #d3d3d3;';
    template = +'            height: 1px;';
    template = +'        }';
    template = +'</style>';
    template = +'</head>';
    template = +'<body header="nlheader" header-height="10%" footer="nlfooter" footer-height="20pt" padding="0.5in 0.5in 0.5in 0.5in" size="Letter">';
    template = +'    <table style="width: 100%; margin-top: 10px;"><tr>';
    template = +'	<td class="addressheader" colspan="3"><b>${record.billaddress@label}</b></td>';
    template = +'	<td class="addressheader" colspan="3"><b>${record.shipaddress@label}</b></td>';
    template = +'	<td class="totalboxtop" colspan="5"><b>${record.total@label?upper_case}</b></td>';
    template = +'	</tr>';
    template = +'	<tr>';
    template = +'	<td class="address" colspan="3" rowspan="2">${record.billaddress}</td>';
    template = +'	<td class="address" colspan="3" rowspan="2">${record.shipaddress}</td>';
    template = +'	<td align="right" class="totalboxmid" colspan="5">${record.total}</td>';
    template = +'	</tr>';
    template = +'	<tr>';
    template = +'	<td align="right" class="totalboxbot" colspan="5"><b>${record.duedate@label}:</b> ${record.duedate}</td>';
    template = +'	</tr></table>';
    template = +'';
    template = +'<table class="body" style="width: 100%; margin-top: 10px;"><tr>';
    template = +'	<th>${record.terms@label}</th>';
    template = +'	<th>${record.duedate@label}</th>';
    template = +'	<th>${record.otherrefnum@label}</th>';
    template = +'	<th>${record.salesrep@label}</th>';
    template = +'	<th>${record.shipmethod@label}</th>';
    template = +'	<th>${record.partner@label}</th>';
    template = +'	</tr>';
    template = +'	<tr>';
    template = +'	<td>${record.terms}</td>';
    template = +'	<td>${record.duedate}</td>';
    template = +'	<td>${record.otherrefnum}</td>';
    template = +'	<td>${record.salesrep}</td>';
    template = +'	<td>${record.shipmethod}</td>';
    template = +'	<td>${record.partner}</td>';
    template = +'	</tr></table>';
    template = +'<#if record.item?has_content>';
    template = +'';
    template = +'<table class="itemtable" style="width: 100%; margin-top: 10px;"><!-- start items --><#list record.item as item><#if item_index==0>';
    template = +'<thead>';
    template = +'	<tr>';
    template = +'	<th align="center" colspan="3">${item.quantity@label}</th>';
    template = +'	<th colspan="12">${item.item@label}</th>';
    template = +'	<th colspan="3">${item.options@label}</th>';
    template = +'	<th align="right" colspan="4">${item.rate@label}</th>';
    template = +'	<th align="right" colspan="4">${item.amount@label}</th>';
    template = +'	</tr>';
    template = +'</thead>';
    template = +'</#if><tr>';
    template = +'	<td align="center" colspan="3" line-height="150%">${item.quantity}</td>';
    template = +'	<td colspan="12"><span class="itemname">${item.item}</span><br />${item.description}</td>';
    template = +'	<td colspan="3">${item.options}</td>';
    template = +'	<td align="right" colspan="4">${item.rate}</td>';
    template = +'	<td align="right" colspan="4">${item.amount}</td>';
    template = +'	</tr>';
    template = +'	</#list><!-- end items --></table>';
    template = +'';
    template = +'<hr /></#if>';
    template = +'<table class="total" style="width: 100%; margin-top: 10px;"><tr>';
    template = +'	<td colspan="4">&nbsp;</td>';
    template = +'	<td align="right"><b>${record.subtotal@label}</b></td>';
    template = +'	<td align="right">${record.subtotal}</td>';
    template = +'	</tr>';
    template = +'	<tr>';
    template = +'	<td colspan="4">&nbsp;</td>';
    template = +'	<td align="right"><b>${record.taxtotal@label} (${record.taxrate}%)</b></td>';
    template = +'	<td align="right">${record.taxtotal}</td>';
    template = +'	</tr>';
    template = +'	<tr class="totalrow">';
    template = +'	<td background-color="#ffffff" colspan="4">&nbsp;</td>';
    template = +'	<td align="right"><b>${record.total@label}</b></td>';
    template = +'	<td align="right">${record.total}</td>';
    template = +'	</tr></table>';
    template = +'</body>';
    template = +'</pdf>';
    renderer.setTemplate(template);
    renderer.addRecord('record', purchRec);
    var xml = renderer.renderToString();
    var file = nlapiXMLToPDF(xml);
    response.setContentType('PDF', 'invoice' + purchRec.getFieldValue("id") + '.pdf', 'inline');
    response.write(file.getValue());
}